- name: install Java-21 & Run SpringBoot
  hosts: myhosts
  become: true

  tasks:
   - name: install java-21-amazon-corretto-devel
     ansible.builtin.dnf:
       name: java-21-amazon-corretto-devel
       state: present

   - name: make dir
     ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'

   - name: copy source code
     ansible.builtin.copy:
        src: ../demo/demo-0.0.1-SNAPSHOT.jar
        dest: /app/demo-0.0.1-SNAPSHOT.jar
        mode: '0644'

   - name: create systemd service
     ansible.builtin.copy:
        dest: /etc/systemd/system/myapp.service
        mode: '0644'
        content: |
          [Unit]
          Description=Spring Boot Application myapp
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory=/app
          ExecStart=/usr/bin/java -jar /app/demo-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

   - name: start myapp
     ansible.builtin.systemd:
        name: myapp
        state: started
        enabled: yes
        daemon_reload: yes
