name: Terraform_Ansible
run-name: Deploy by Terraform & nginx by Ansible

on:
  push:
    branches:
      - main
    paths:
      - 'lecture43/**/*.tf'
      - 'lecture43/terraform/*tftest.hcl'
      - '.github/workflows/terraform_ansible.yml'
      - 'lecture43/ansible/playbook.yml'
      - 'lecture43/ansible/inventory.tpl'
  pull_request:
    paths:
      - 'lecture43/**/*.tf'
      - 'lecture43/terraform/*tftest.hcl'
      - '.github/workflows/terraform_ansible.yml'
      - 'lecture43/ansible/playbook.yml'
      - 'lecture43/ansible/inventory.tpl'
  workflow_dispatch:

jobs:
  Terraform_Ansible_deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
      TF_VAR_key_name: ${{ secrets.key_name }}
      ANSIBLE_HOST_KEY_CHECKING: "False"

    defaults:
      run:
        working-directory: ./lecture43
  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: init
        run: terraform init
        working-directory: lecture43/terraform

      - name: Validate
        run: terraform validate
        working-directory: lecture43/terraform

      - name: plan
        run: terraform plan
        working-directory: lecture43/terraform

      - name: apply
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: lecture43/terraform

      - name: Install Ansible
        run: sudo apt install ansible -y
        working-directory: lecture43/ansible

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
        working-directory: lecture43/ansible
      
      - name: Get EC2_ip
        run: echo "EC2_ip=$(terraform output -raw instance_ip)" >> $GITHUB_ENV
        working-directory: lecture43/terraform

      - name: Prepare Inventory_file
        run: sed "s/EC2_ip/${{ env.EC2_ip }}/" inventory.tpl > inventory.ini
        working-directory: lecture43/ansible

      - name: Syntax check
        run: ansible-playbook --syntax-check -i inventory.ini playbook.yml 
        working-directory: lecture43/ansible

      - name: Dry run
        run: ansible-playbook --check -i inventory.ini playbook.yml
        working-directory: lecture43/ansible

      - name: Apply
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ansible-playbook -i inventory.ini playbook.yml
        working-directory: lecture43/ansible
