name: Terraform CI/CD
run-name: Deploy by Terraform

on:
  push:
    paths:
      - 'lecture33/**.tf'
      - 'lecture33/modules/**tftest.hcl'
      - 'lecture33/.github/workflows/*.yaml'
  pull_request:
    paths:
      - 'lecture33/**.tf'
      - 'lecture33/modules/**tftest.hcl'
      - 'lecture33/.github/workflows/*.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-northeast-1
    
    defaults:
      run:
        working-directory: lecture33
  
    steps:
      - uses: actions/checkout@v4

      - name: init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: plan
        run: terraform plan

      - name: apply
        run: terraform apply -auto-approve
